import os
import uuid
from fpdf import FPDF
from datetime import datetime

class CTraceReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(16, 185, 129) # Emerald Green
        self.cell(0, 10, 'C-Trace Executive Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
        self.cell(0, 10, f'Generated on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'R')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(50)
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)

    def chapter_body(self, body):
        self.set_font('Helvetica', '', 12)
        self.set_text_color(0)
        # Sanitize body text for FPDF (latin-1 only by default)
        clean_body = body.encode('latin-1', 'replace').decode('latin-1')
        self.multi_cell(0, 8, clean_body)
        self.ln()

def generate_pdf_report(data):
    pdf = CTraceReport()
    pdf.add_page()

    # Executive Summary Section
    pdf.chapter_title("Executive Summary")
    total_emissions = f"{data['total_emission']:.2f}"
    pdf.set_font('Helvetica', '', 12)
    pdf.cell(0, 10, f"Total Emissions to Date: {total_emissions} kg CO2e", 0, 1)
    pdf.ln(5)

    # Scope Breakdown Section
    pdf.chapter_title("Emission Breakdown by Scope")
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(60, 10, 'Scope', 1, 0, 'C', 1)
    pdf.cell(60, 10, 'Emissions (kg CO2e)', 1, 0, 'C', 1)
    pdf.cell(60, 10, '% of Total', 1, 1, 'C', 1)
    
    pdf.set_font('Helvetica', '', 12)
    if 'by_scope' in data:
        for scope, value in data['by_scope']:
            ratio = data.get('scope_ratios', {}).get(scope, 0)
            clean_scope = scope.encode('latin-1', 'replace').decode('latin-1')
            pdf.cell(60, 10, clean_scope, 1)
            pdf.cell(60, 10, f"{value:.2f}", 1)
            pdf.cell(60, 10, f"{ratio:.1f}%", 1, 1)
    pdf.ln(10)

    # AI Insights Section
    pdf.chapter_title("AI-Driven Reduction Strategies")
    if 'insights' in data:
        for insight in data['insights']:
            # Title
            pdf.set_font('Helvetica', 'B', 12)
            # Determine color based on badge type roughly
            if insight.get('badge') == 'Priority':
                pdf.set_text_color(220, 38, 38) # Red
            elif insight.get('badge') == 'Opportunity' or insight.get('badge') == 'High Impact':
                pdf.set_text_color(16, 185, 129) # Green
            else:
                pdf.set_text_color(0)
            
            title = insight['title'].encode('latin-1', 'replace').decode('latin-1')
            badge = insight.get('badge', 'Insight').encode('latin-1', 'replace').decode('latin-1')
            pdf.cell(0, 8, f"{title} ({badge})", 0, 1)
            
            # Description
            pdf.set_font('Helvetica', '', 11)
            pdf.set_text_color(80)
            desc = insight['desc'].encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6, desc)
            pdf.ln(4)

    # Add a closing note
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 10)
    pdf.set_text_color(100)
    pdf.multi_cell(0, 5, "This report was automatically generated by the C-Trace Analysis Engine based on verified invoice data.")

    # Return PDF as bytes
    # dest='S' returns the document as a string. We encode it to bytes.
    try:
        pdf_string = pdf.output(dest='S')
        # In some fpdf versions output returns bytes, in others string. 
        # If it's already bytes, fine. If string, encode.
        if isinstance(pdf_string, str):
            return pdf_string.encode('latin-1')
        return pdf_string
    except Exception as e:
        # Fallback for newer fpdf2 versions or different behavior
        print(f"PDF Generation Error: {e}")
        # Try returning bytearray if implicit
        return pdf.output().encode('latin-1')
